name: Sync Fork

on:
  schedule:
    - cron: '0 21 * * *' # Runs at 21:00 UTC every day.
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: helium
          base: main
          head: main
          auto_approve: true
          token: ${{ secrets.PERSONAL_TOKEN }}
